### ISSUE TITLE
support for python 3.11?

### ISSUE THREAD

**Issue by aviadr1** [Happy-Kunal/pydantic2avro#1]
can you support earlier versions of python, specifically 3.11?
I think  probably just changing the line in your `pyproject.toml` that specifies python 3.12 as minimal is the only thing that needs to change

**Comment by Happy-Kunal** [comment]
Good suggestion! 🚀,
I ran the test with Python 3.11, and it’s all running smoothly. Everything’s looking great! 👍

**Comment by Happy-Kunal** [comment]
Just a quick update: [pydantic2avro v0.4.0](https://pypi.org/project/pydantic2avro/0.4.0/) now supports Python 3.11! 🎉 If you’re using the latest version, you’re all set to take advantage of this compatibility
