### ISSUE TITLE
What uniqueness? 

### ISSUE THREAD

**Issue by devova** [Happy-Kunal/pydantic2avro#2]
I was always using https://github.com/godatadriven/pydantic-avro and now I wonder...
- why do we have another package that do the same thing but just with other interface?
- maybe it worth to invest the effort into original idea to polish it faster, rather than create own package?

**Comment by Happy-Kunal** [comment]
Hello @devova ,

Thanks for showing your interest in `pydantic2avro`! I’m sorry for the delayed response; I was caught up with some urgent tasks.

You’ve asked a great question! While there are **some similarities there are some significant differences as well** (such as more options to customize output avro schema), but I think the detailed answer will make more sense after publishing a detailed documentation on how to use `pydantic2avro` to its fullest. Currently **detailed documentation is still work in progress** and I am actively working on it. I will let you know once it's done and our discussion afterwards might lead to significant improvement in quality of documentation.

Thanks for your patience and enthusiasm. Looking forward to diving deeper with you soon!,
Best regards,
Kunal Sharma
